language: python
python:
#  - "2.7" #todo: 2.7 only has a few tests failing
  - "3.4"
  - "3.5"
  - "nightly" # currently points to 3.6-dev
install:
  - pip install requests
script:
  - python setup.py sdist
  - python setup.py test
