language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --ignore=E501,E225 projectoxford"
  - pyflakes -x W projectoxford
script:
  - python setup.py sdist
  - python setup.py test